# Generated by Django 2.2.4 on 2019-09-01 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_movie_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(default='movies/images/default.jpg', upload_to='movies/images/'),
        ),
    ]
