# Generated by Django 2.2.4 on 2019-09-15 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20190901_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(default='movies/images/default.jpg', upload_to='images/'),
        ),
    ]
