# Generated by Django 2.2.4 on 2019-09-15 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_auto_20190915_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='date_added',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(default='images/default.jpg', upload_to='images/'),
        ),
    ]
