# Generated by Django 2.2.4 on 2019-10-16 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_auto_20190915_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=180), max_length=200, unique=True),
        ),
    ]
