# Generated by Django 2.2.4 on 2019-09-15 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_auto_20190915_1545'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'get_latest_by': 'date_added'},
        ),
        migrations.AddField(
            model_name='movie',
            name='hit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
