# Generated by Django 2.2.4 on 2019-10-16 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0016_remove_movie_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='slug',
            field=models.SlugField(default='slug-null', max_length=200),
        ),
    ]
