# Generated by Django 3.2.5 on 2021-07-26 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0021_alter_movie_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='cover',
            field=models.URLField(default='images/default.jpg'),
        ),
    ]
