# Generated by Django 3.2.5 on 2021-07-28 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0022_movie_cover'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribers',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
        ),
    ]
